name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Cache references
      uses: actions/cache@v2
      with:
        path: cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install dependencies
      run: |
        git submodule update --init --recursive && make clean
        make venv
    - name: Build figures
      run: make all -j 3
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: output/*.*
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages # The branch the action should deploy to.
        single-commit: true
        folder: output # The folder the action should deploy.
